export const catalogItems = [
  { id: 1,  category: 'fencing',    categoryLabel: 'Заборы',         icon: '🔩', title: 'Забор из профнастила',        price: 'от 1 800 ₽/м.п.' },
  { id: 2,  category: 'fencing',    categoryLabel: 'Заборы',         icon: '🔩', title: 'Забор из сетки рабицы',        price: 'от 800 ₽/м.п.' },
  { id: 3,  category: 'fencing',    categoryLabel: 'Заборы',         icon: '🔩', title: 'Забор из евроштакетника',      price: 'от 2 200 ₽/м.п.' },
  { id: 4,  category: 'foundation', categoryLabel: 'Фундаменты',    icon: '⚓', title: 'Свайное поле — винтовые сваи', price: 'от 3 500 ₽/свая' },
  { id: 5,  category: 'foundation', categoryLabel: 'Фундаменты',    icon: '⚓', title: 'Свайное поле — забивные сваи', price: 'от 4 500 ₽/свая' },
  { id: 6,  category: 'foundation', categoryLabel: 'Фундаменты',    icon: '💧', title: 'Септик под ключ',              price: 'от 45 000 ₽' },
  { id: 7,  category: 'build',      categoryLabel: 'Строительство', icon: '🏠', title: 'Жилой дом под ключ',           price: 'от 35 000 ₽/м²' },
  { id: 8,  category: 'build',      categoryLabel: 'Строительство', icon: '🏗️', title: 'Техническое здание',           price: 'от 18 000 ₽/м²' },
  { id: 9,  category: 'build',      categoryLabel: 'Строительство', icon: '🏗️', title: 'Коспострой',                   price: 'от 120 000 ₽' },
  { id: 10, category: 'utility',    categoryLabel: 'Хозпостройки',  icon: '📦', title: 'Бытовка металлическая',        price: 'от 65 000 ₽' },
  { id: 11, category: 'utility',    categoryLabel: 'Хозпостройки',  icon: '📦', title: 'Бытовка деревянная',           price: 'от 80 000 ₽' },
  { id: 12, category: 'utility',    categoryLabel: 'Хозпостройки',  icon: '🐕', title: 'Вольер для собак',             price: 'от 25 000 ₽' },
  { id: 13, category: 'utility',    categoryLabel: 'Хозпостройки',  icon: '🐔', title: 'Курятник / птичник',           price: 'от 30 000 ₽' },
  { id: 14, category: 'supply',     categoryLabel: 'Снабжение',     icon: '🚛', title: 'Строительные материалы',       price: 'По запросу' },
  { id: 15, category: 'supply',     categoryLabel: 'Снабжение',     icon: '🚛', title: 'Оборудование',                 price: 'По запросу' },
  { id: 16, category: 'tech',       categoryLabel: 'Техника',       icon: '🚜', title: 'Экскаватор с оператором',      price: 'от 2 500 ₽/час' },
  { id: 17, category: 'tech',       categoryLabel: 'Техника',       icon: '🚛', title: 'Самосвал',                     price: 'от 3 000 ₽/рейс' },
]
